### ISSUE TITLE
where to download the jar file?

### ISSUE THREAD

**Issue by lilly-chen** [titicaca/spark-iforest#13]
hi,

where i can download the spark-iforest.jar file ?

Thanks!

**Comment by titicaca** [comment]
You can build your spark-iforest.jar by following https://github.com/titicaca/spark-iforest/tree/master/python#install

**Comment by yaakovML** [comment]
hi,

I followed your guideline and got:

iforest = IForest(contamination=0.3, maxDepth=2)
Traceback (most recent call last):
  File "/Users/htayeb/miniconda2/envs/cs/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-757f1fc182c0>", line 1, in <module>
    iforest = IForest(contamination=0.3, maxDepth=2)
  File "/Users/htayeb/miniconda2/envs/cs/lib/python2.7/site-packages/pyspark/__init__.py", line 110, in wrapper
    return func(self, **kwargs)
  File "/Users/htayeb/miniconda2/envs/cs/lib/python2.7/site-packages/pyspark_iforest/ml/iforest.py", line 245, in __init__
    self._java_obj = self._new_java_obj("org.apache.spark.ml.iforest.IForest", self.uid)
  File "/Users/htayeb/miniconda2/envs/cs/lib/python2.7/site-packages/pyspark/ml/wrapper.py", line 67, in _new_java_obj
    return java_obj(*java_args)
TypeError: 'JavaPackage' object is not callable

any idea why?

I am using python 2.7 and the spark context is alive.
