### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by kezpitt** [titicaca/spark-iforest#22]
I am running the python example provided, but got the following error: 
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Traceback (most recent call last):
  File "/Users/kzhang/repositories/flightaware/data/ml_features/spark-iforest.py", line 19, in <module>
    iforest = IForest(contamination=0.3, maxDepth=2)
  File "/Users/kzhang/anaconda3/lib/python3.7/site-packages/pyspark/__init__.py", line 110, in wrapper
    return func(self, **kwargs)
  File "/Users/kzhang/anaconda3/lib/python3.7/site-packages/pyspark_iforest/ml/iforest.py", line 245, in __init__
    self._java_obj = self._new_java_obj("org.apache.spark.ml.iforest.IForest", self.uid)
  File "/Users/kzhang/anaconda3/lib/python3.7/site-packages/pyspark/ml/wrapper.py", line 67, in _new_java_obj
    return java_obj(*java_args)
TypeError: 'JavaPackage' object is not callable

**Comment by titicaca** [comment]
You can follow the guide for pyspark-iforest:
https://github.com/titicaca/spark-iforest/tree/master/python

By the way, note that the spark and pysaprk version should be 2.4.x
