### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.api.client.Client

### ISSUE THREAD

**Issue by flybird101** [titicaca/spark-iforest#27]
**In Spark local mode, it's ok. But in spark yarn mode, it was failed.**

When I run fllowing code:
**val predictions = model.transform(dataset) //the code before this line is ok.**

**//The error information:**
Name: java.lang.NoClassDefFoundError
Message: Lcom/sun/jersey/api/client/Client;
StackTrace:   at java.lang.Class.getDeclaredFields0(Native Method)
  at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
  at java.lang.Class.getDeclaredFields(Class.java:1916)
  at org.apache.spark.util.SizeEstimator$.getClassInfo(SizeEstimator.scala:330)
  at org.apache.spark.util.SizeEstimator$.visitSingleObject(SizeEstimator.scala:222)
  at org.apache.spark.util.SizeEstimator$.org$apache$spark$util$SizeEstimator$$estimate(SizeEstimator.scala:201)
  at org.apache.spark.util.SizeEstimator$.estimate(SizeEstimator.scala:69)
  at org.apache.spark.util.collection.SizeTracker$class.takeSample(SizeTracker.scala:78)
  at org.apache.spark.util.collection.SizeTracker$class.afterUpdate(SizeTracker.scala:70)
  at org.apache.spark.util.collection.SizeTrackingVector.$plus$eq(SizeTrackingVector.scala:31)
  at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1039)
  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1030)
  at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:970)
  at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1030)
  at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:793)
  at org.apache.spark.storage.BlockManager.putSingle(BlockManager.scala:1351)
  at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:122)
  at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:88)
  at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
  at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:56)
  at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1488)
  at org.apache.spark.ml.iforest.IForestModel.transform(IForest.scala:77)
  at org.apache.spark.ml.PipelineModel$$anonfun$transform$1.apply(Pipeline.scala:305)
  at org.apache.spark.ml.PipelineModel$$anonfun$transform$1.apply(Pipeline.scala:305)
  at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
  at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
  at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
  at org.apache.spark.ml.PipelineModel.transform(Pipeline.scala:305)
  ... 46 elided
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.api.client.Client
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Then I google this error, I find my $SPARK_HOME/jars/ have those jars about jersey:**
jersey-client-2.22.2.jar                  jersey-container-servlet-core-2.22.2.jar  jersey-server-2.22.2.jar                  jetty-util-6.1.26.cloudera.4.jar
jersey-common-2.22.2.jar                  jersey-guava-2.22.2.jar                   jets3t-0.9.3.jar                          
jersey-container-servlet-2.22.2.jar       jersey-media-jaxb-2.22.2.jar              jetty-6.1.26.cloudera.4.jar       

**So, I set the first code line like this:**
val spark = SparkSession
.builder()
.master("yarn") //  yarn mode
.appName("iforest example")
.config("spark.jars", "../spark-iforest-2.2.0.jar,../jersey-client-2.22.2.jar")
.getOrCreate()

**But it didn't work, the error information was all the same.**

**Comment by flybird101** [comment]
copy /usr/lib/hadoop-yarn/lib/ 
ersey-client-1.9.jar  jersey-core-1.9.jar    jersey-guice-1.9.jar   jersey-json-1.9.jar    jersey-server-1.9.jar 
to /opt/app/spark/jars/  is ok
