### ISSUE TITLE
Getting NoSuchMethodError in IForest.fit

### ISSUE THREAD

**Issue by blackvvine** [titicaca/spark-iforest#29]
Hi, I'm getting the exact same error as [issue #5](https://github.com/titicaca/spark-iforest/issues/5) in version 2.4.0 with Spark 2.4 at runtime, although the tests all pass.

```python
iforest = IForest(contamination=0.3, maxDepth=2)
model = iforest.fit(nz_df)
```

Results:

```
Py4JJavaError: An error occurred while calling o161.fit.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.Instrumentation$.instrumented(Lscala/Function1;)Ljava/lang/Object;
	at org.apache.spark.ml.iforest.IForest.fit(IForest.scala:495)
	at org.apache.spark.ml.iforest.IForest.fit(IForest.scala:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

Any ideas what could the problem be?

**Comment by titicaca** [comment]
make sure you have move your built jar to your spark java home.

**Comment by blackvvine** [comment]
Thank you, it was a mistake on my side. The PySpark distribution version was 2.4 but yarn classpath had Spark 2.2 jars in it.
