### ISSUE TITLE
PySpark iforest.fit() method error

### ISSUE THREAD

**Issue by victorming666** [titicaca/spark-iforest#48]
Spark version: 2.3.2
Python: 3.6

> Exception ignored in: <object repr() failed>
> Traceback (most recent call last):
>   File "/usr/hdp/current/spark-client/python/pyspark/ml/wrapper.py", line 105, in __del__
>     SparkContext._active_spark_context._gateway.detach(self._java_obj)
> AttributeError: 'IForest' object has no attribute '_java_obj'
> 
> ---------------------------------------------------------------------------
> Py4JJavaError                             Traceback (most recent call last)
> <ipython-input-31-7e4a96618ba5> in <module>
>      24 
>      25 # 训练模型
> ---> 26 model = iforest.fit(powerDF4)
>      27 
>      28 # 模型总结
> 
> /usr/hdp/current/spark-client/python/pyspark/ml/base.py in fit(self, dataset, params)
>     130                 return self.copy(params)._fit(dataset)
>     131             else:
> --> 132                 return self._fit(dataset)
>     133         else:
>     134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "
> 
> /usr/hdp/current/spark-client/python/pyspark/ml/wrapper.py in _fit(self, dataset)
>     286 
>     287     def _fit(self, dataset):
> --> 288         java_model = self._fit_java(dataset)
>     289         model = self._create_model(java_model)
>     290         return self._copyValues(model)
> 
> /usr/hdp/current/spark-client/python/pyspark/ml/wrapper.py in _fit_java(self, dataset)
>     283         """
>     284         self._transfer_params_to_java()
> --> 285         return self._java_obj.fit(dataset._jdf)
>     286 
>     287     def _fit(self, dataset):
> 
> /usr/hdp/current/spark-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
>    1255         answer = self.gateway_client.send_command(command)
>    1256         return_value = get_return_value(
> -> 1257             answer, self.gateway_client, self.target_id, self.name)
>    1258 
>    1259         for temp_arg in temp_args:
> 
> /usr/hdp/current/spark-client/python/pyspark/sql/utils.py in deco(*a, **kw)
>      61     def deco(*a, **kw):
>      62         try:
> ---> 63             return f(*a, **kw)
>      64         except py4j.protocol.Py4JJavaError as e:
>      65             s = e.java_exception.toString()
> 
> /usr/hdp/current/spark-client/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
>     326                 raise Py4JJavaError(
>     327                     "An error occurred while calling {0}{1}{2}.\n".
> --> 328                     format(target_id, ".", name), value)
>     329             else:
>     330                 raise Py4JError(
> 
> Py4JJavaError: An error occurred while calling o850.fit.
> : java.lang.NoSuchMethodError: org.apache.spark.ml.util.Instrumentation$.instrumented(Lscala/Function1;)Ljava/lang/Object;
> 	at org.apache.spark.ml.iforest.IForest.fit(IForest.scala:495)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:750)
>

**Comment by titicaca** [comment]
You can try with https://github.com/titicaca/spark-iforest/releases/tag/v2.3.0 if you use spark version 2.3.x
